### ISSUE TITLE
Neovim crashes when opening more than 5 buffers

### ISSUE THREAD

**Issue by sayit358** [jose-elias-alvarez/buftabline.nvim#18]
When opening more than 5 buffers with icons enabled, Neovim gets terminated with the message `realloc(): invalid next size`.

**Comment by jose-elias-alvarez** [comment]
Thanks for reporting this! I haven’t seen anything like this on my end, so could I ask you for a little more information to help debug this?

1. Does this always happen exactly with 6+ buffers, regardless of file name / extension? 
2. What happens if you remove icons from your format? Is there still a limit on the number of buffers you can open before a crash?
3. Does the problem occur when you isolate the plugin?

It sounds to me like it may be a Neovim issue, since the plugin doesn’t do anything fancy with Lua, but more information could lead to a hint (or at least something more concrete that we can report upstream).

**Comment by sayit358** [comment]
Your commit fixed the issue and it works fine. Closing the issue now. Thanks!
