### ISSUE TITLE
tabline not updated to clear modified flags after saving all buffers (:wa)

### ISSUE THREAD

**Issue by jdrouhard** [jose-elias-alvarez/buftabline.nvim#21]
I just started using your plugin today after scouring the internet for something exactly like this! Thank you so much. If I didn't find your plugin within another day or two, I'd have likely set out to write the exact same thing.

Anyway, there's a couple minor issues I've seen. Here's the first one:

![image](https://user-images.githubusercontent.com/394891/128765603-aa0347f1-2221-4936-8027-ac45a1ccaecc.png)

If multiple buffers are modified (the first two buffers in the screenshot), but the active buffer is not actually modified, then evoking a `:wa` to save all buffers doesn't update the tabline to clear the modified highlights/modifiers. If I then move to a different buffer, the whole tabline updates. If I call `:wa` from a buffer that is modified, the tabline updates appropriately.

This is probably a missed autocmd event, but I'm not familiar enough with all of them to know which one needs to be added.

**Comment by jose-elias-alvarez** [comment]
This is actually an issue with the `BufModifiedSet` event, which only triggers for the current buffer (despite what the documentation says). There's an [open PR](https://github.com/neovim/neovim/pull/13247) to fix the event, but until that's merged, I think the fix is to also update on `BufWritePost`.
