### ISSUE TITLE
Start screen is erased when nvim is opened and this plugin loads

### ISSUE THREAD

**Issue by jdrouhard** [jose-elias-alvarez/buftabline.nvim#22]
The start/help screen that displays in the middle of the window when you first open nvim is erased immediately when this plugin is loaded. Typically this is a misbehaving redraw or autocmd handler, but haven't been able to pinpoint exactly where it's occurring.

```lua
-- plugins.lua (using packer.nvim)

use {
    'jose-elias-alvarez/buftabline.nvim',
    --opt = true,
    requires = 'kyazdani42/nvim-web-devicons',
    config = [[require'config.buftabline']]
}
```
Toggling `opt` (so disabling it on start) fixes the issue, so I know the issue is this plugin somehow.

**Comment by jose-elias-alvarez** [comment]
You're right, and it looks like it's the initial render triggered by `BufEnter`. However, it looks like changing `tabline` after Vim / Neovim has started will clear the start screen. You can try it by running `nvim -u NONE -c "set showtabline=2"`, then calling `:set tabline=""`.

It looks like setting `tabline` at startup (from the command line or `init.vim`) keeps the start screen, but since all of the plugin's updates are scheduled, it'll always get cleared shortly after start. Not sure what we can do about this, and I don't know if I consider it a priority, but I'm open to fixes.
