### ISSUE TITLE
[feature suggestion] auto-hide

### ISSUE THREAD

**Issue by konradmalik** [jose-elias-alvarez/buftabline.nvim#4]
Hi,
Thanks for this great plugin. I very much agree with your "Inspiration" section and keeping this one simple, this is exactly why I choose this plugin over the others 😉 

I have just 1 suggestion for a new feature. Feel free to close this if it is against your idea of what this plugin should be. Cannot really open a PR for this as I don't know lua unfortunately.

The new feature would be "auto-hide" functionality that is present in for example [barbar.nvim](https://github.com/romgrk/barbar.nvim). It would hide the tabline when there is only 1 buffer open, and show it whenever there is more. Seems like the only thing that is missing for me right now.

**Comment by jose-elias-alvarez** [comment]
Thanks for the feedback! It would be a nice feature to save screen space, and since the plugin already supports toggling the tabline, it should be pretty simple. I'll take a look at how barbar implemented it and work on it this weekend.

**Comment by jose-elias-alvarez** [comment]
I had a little time today and put this together. barbar's implementation wasn't going to work, since this plugin doesn't do anything after setting the tabline (and Neovim doesn't run the tabline function when the tabline is hidden), so I used autocommands. 

It definitely works when opening / closing individual files, and I *think* it should work for batch `:edit` commands from file picker plugins, but let me know.

**Comment by konradmalik** [comment]
thanks! works great, haven't noticed any bugs yet :+1:
